### ISSUE TITLE
Gsettings schema problems on drawspaces

### ISSUE THREAD

**Issue by tonurics** [rezso/pluma-plugins#1]
(pluma:20782): GLib-GIO-ERROR **: Settings schema 'org.mate.pluma.plugins.drawspaces' is not installed

Looks like the wrong path might have been used: /apps/pluma/plugins/drawspaces when it should probably be /org/mate/pluma/plugins/drawspaces

showtabbar is also showing up in /apps/pluma/plugins/

**Comment by rezso** [comment]
Fixed in https://github.com/rezso/pluma-plugins/commit/ae00d3f34755a1c89bc74ced6b2b25b874e68a37, thanks.
